### ISSUE TITLE
Fix & Finalize Dependencies

### ISSUE THREAD

**Issue by qiancao** [Novartis/torchsurv#1]
**TorchSurv**

- torch
- scipy
- torchmetrics

**Docs**

- sphinx
- myst-parser
- nbsphinx
- sphinxcontrib-bibtex
- sphinx-book-theme
- pandoc

**Tests and Examples**

- lifelines
- sksurv
- torchmatrix
- pytorch_lightning (and lightning)

**Comment by kruscpe1** [comment]
Dependencies now included for basic torchsurv installation -> you can try `pip install torchsurv` to see if this works as expected.

**Comment by kruscpe1** [comment]
Remaining tasks:

- [ ] Update pyproject.toml to include only core dependencies:
  - torch
  - scipy
  - torchmetrics
 - [ ] document additional dependencies to run notebooks s.t. users know how to run these
