### ISSUE TITLE
conda

### ISSUE THREAD

**Issue by tcoroller** [Novartis/torchsurv#32]
create conda forge release

**Comment by tcoroller** [comment]
@pkrusche https://www.pyopensci.org/python-package-guide/tutorials/publish-conda-forge.html

**Comment by tcoroller** [comment]
Following this: https://github.com/conda-forge/staged-recipes

**Comment by kruscpe1** [comment]
https://github.com/conda-forge/staged-recipes/pull/27124

@tcoroller can you confirm there you can be a maintainer?
