### ISSUE TITLE
Fix relative links in README and duplicated docs

### ISSUE THREAD

**Issue by kruscpe1** [Novartis/torchsurv#4]

**Comment by tcoroller** [comment]
- Import tools validation function by mistake in other functions
- Disapearing tab for `related packages`

![Screenshot 2024-04-12 at 8 54 32 AM](https://github.com/Novartis/torchsurv/assets/14895385/2b982bd4-36be-454d-854f-f8bae5fb5002)
![Screenshot 2024-04-12 at 8 54 26 AM](https://github.com/Novartis/torchsurv/assets/14895385/bca09a7b-9ae8-46f5-9a90-1ea13196dd50)
