### ISSUE TITLE
Deep learning under log likelihood loss does not converge easily.

### ISSUE THREAD

**Issue by Minxiangliu** [Novartis/torchsurv#40]
Hi here,
Thank you for the tool, I'm currently trying to train 3D brain medical images, and I am using the `DenseNet121` model and the `neg_partial_log_likelihood` loss function, and everything is normal, but when I observe the training and validation loss values, I find that the validation loss value cannot effectively converge, and there is even a trend of rising, and I have tried many different ways to reduce overfitting, including: data augmentation, dropout, over sampling, etc., the validation loss value is still not easy to converge, please ask this is a problem with the data itself, or have I overlooked some details?

A total of 189 3D images

![image](https://github.com/Novartis/torchsurv/assets/30144428/ff6ffc54-e06b-44c9-9c02-f858b300acd7)
![image](https://github.com/Novartis/torchsurv/assets/30144428/e3f2bb30-b78a-44d9-ac78-a5ae4c6eac1b)

**Comment by tcoroller** [comment]
Dear @Minxiangliu , thank you for you question. 
At first glance, it may be an **experimental issue (overfitting)** rather than a `TorchSurv` loss function issue. 

Couple comments that may help you

1. `Pick the right loss`: when using `cox` model, the **model optimize by ranking samples within a batch**. The larger the batch, the more reliable the loss estimation will be. When using medical image however, it may be hard to have a batch size greater than 8 samples due to GPU memory limits. Two suggestions for you: You can instead try the [Weibull model](https://opensource.nibr.com/torchsurv/_autosummary/torchsurv.loss.weibull.html), **which does not rank but fit a distribution for each sample**. It removes batch size dependancies, which is good for you. If you want to keep `cox` model, then you should try our [Momentum loss](https://opensource.nibr.com/torchsurv/_autosummary/torchsurv.loss.momentum.html), which **uses two networks (online and target) alongside a dynamic memory bank** (like MoCo for contrastive learning). We have a [tutorial notebook here](https://opensource.nibr.com/torchsurv/notebooks/momentum.html).
3. `Data / Inputs`: You are using 189 3D images to predict a time to event target. This may be under sampled for the task. Try to reduce the covariates size (e.g., reduce image dimension, use embeddings, ..). What is your target? How many censored/non-censored patients do you have? Is there any other covariates (e.g., clinical) you can use to help the model? Is there literature on the topic that shown signal?
4. `Modeling parameters`: What is your training/validation split? What is your batch size? And your learning rate (the loss profile looks "jumpy)? **Your training loss is decreasing close to 0, so its learning something but it is indeed very much overfitting**. There are plenty of [external ressources](https://discuss.pytorch.org/t/how-to-prevent-overfitting/1902) on overfitting that you can read and learn from. 

Good luck for your project and thank you for using `TorchSurv`!

**Comment by tcoroller** [comment]
Dear @Minxiangliu, 

Thanks for sharing the details on your experiment. **Overfitting a model** (see your validation loss increasing after a while) **is common for any deep learning models** and there are plenty techniques to mitigate them. You reach a `c-index` of 0.72 during the training, which is fairly encouraging to prove that there is signal. 

Couple small comments for you: 
- `do not round the time to event` (especially if they are in years!), you will simply create ties and make it much harder for the model to rank sample by risk (if they have the same time, the risk should be the same when experiencing the event). 
- 'compare Weibull vs Cox`: switching loss may help in some cases, do no forget that `Weibull` expect two values while `Cox` only one.

**Comment by tcoroller** [comment]
@Minxiangliu could you please you replicate and share the errors for this? 
`[...] if the batch size is less than 16, the model training will encounter errors. It took me some time to identify this issue.`

**Comment by Minxiangliu** [comment]
Hi @tcoroller ,
Thank you for your comment.

I would like to clarify that I only round the time when splitting the data into training and testing sets, merely to ensure better distribution of the data. The original time and event data are used during model training.

Additionally, here is the error I encountered after modifying this example[[1](https://github.com/Novartis/torchsurv/blob/main/docs/notebooks/helpers_introduction.py)][[2](https://github.com/Novartis/torchsurv/blob/main/docs/notebooks/helpers_momentum.py)]. If the `BATCH_SIZE` is set to 160 or above, training proceeds normally. If it is set below 160, an error occurs.

### helpers_momentum.py
```py
import lightning as L
import torch
from torch.utils.data import DataLoader, Dataset
from torchsurv.metrics.cindex import ConcordanceIndex

class CustomDataset(Dataset):
    def __init__(self):
        self.images = torch.rand((1000,1,32,32))
        self.labels = torch.cat((
            torch.zeros((100,)),
            torch.zeros((100,))+1,
            torch.zeros((100,))+2,
            torch.zeros((100,))+3,
            torch.zeros((100,))+4,
            torch.zeros((100,))+5,
            torch.zeros((100,))+6,
            torch.zeros((100,))+7,
            torch.zeros((100,))+8,
            torch.zeros((100,))+9,
        ),dim=0)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        return self.images[idx], self.labels[idx]


class LitMomentum(L.LightningModule):

    def __init__(self, backbone):
        super().__init__()
        # Set our init args as class attributes
        self.learning_rate = 1e-3
        self.num_workers = 2

        # Model evaluation
        self.cindex = ConcordanceIndex()

        # Momentum
        self.model = backbone

    # Lightning related behaviors:

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.learning_rate)
        return optimizer

    def forward(self, x, event, time):
        return self.model(x, event, time)

    def training_step(self, batch, batch_idx):
        x, y = batch
        y[y == 0] = 10  # Offset 0 to prevent log(0)
        loss = self(x, torch.ones_like(y, device=y.device).bool(), y.float())
        self.log("loss", loss, prog_bar=True, on_step=True, on_epoch=True)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        y[y == 0] = 10  # Offset 0 to prevent log(0)
        loss = self(x, torch.ones_like(y, device=y.device).bool(), y.float())
        log_hz_k = self.model.target(x)
        cindex = self.cindex(
            log_hz_k, torch.ones_like(y, device=y.device).bool(), y.float()
        )
        self.log("val_loss", loss, prog_bar=True, on_step=True, on_epoch=True)
        self.log(
            "cindex",
            cindex,
            prog_bar=True,
            on_step=True,
            on_epoch=True,
        )
        return loss

    def test_step(self, batch, batch_idx):
        # Here we just reuse the validation_step for testing
        return self.validation_step(batch, batch_idx)


class MNISTDataModule(L.LightningDataModule):
    def __init__(self, batch_size: int = 32, transforms=None, num_workers: int = 2):
        super().__init__()
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.transforms = transforms

    def setup(self, stage=None):
        # Assign train/val datasets for use in dataloaders
        if stage == "fit" or stage is None:        
            self.train_ds = CustomDataset()
            self.val_ds = CustomDataset()
            
        # Assign test dataset for use in dataloader(s)
        if stage == "test" or stage is None:
            self.test_ds = CustomDataset()

    def train_dataloader(self):
        return DataLoader(
            self.train_ds,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            persistent_workers=True,
            shuffle=True, drop_last=True
        )

    def val_dataloader(self):
        return DataLoader(
            self.val_ds,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            persistent_workers=True,
            shuffle=False, drop_last=False
        )

    def test_dataloader(self):
        return DataLoader(
            self.test_ds,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            persistent_workers=True,
            shuffle=False, drop_last=False
        )
```

### main.py
```py
import warnings, sys
warnings.filterwarnings("ignore")

import torch
torch.set_float32_matmul_precision('high')

from torchsurv.loss.cox import neg_partial_log_likelihood
from torchsurv.loss.momentum import Momentum
from torchvision.transforms import v2
from torchvision.models import resnet18
from helpers_momentum import MNISTDataModule, LitMomentum

import lightning as L
from lightning.pytorch import seed_everything
_ = seed_everything(123, workers=True)

BATCH_SIZE = 160  # batch size for training
EPOCHS = 2  # number of epochs to train

transforms = v2.Compose(
    [
        v2.ToDtype(torch.float32, scale=True),
        v2.Resize(224, antialias=True),
        v2.Normalize(mean=(0,), std=(1,)),
    ]
)

resnet = resnet18(weights=None)
# Fits grayscale images
resnet.conv1 = torch.nn.Conv2d(
    1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
)
# Output log hazards
resnet.fc = torch.nn.Linear(in_features=resnet.fc.in_features, out_features=1)

FACTOR = 10  # Number of batch to keep in memory. Increase our training batch size artificially by factor of 10 here
resnet_momentum = Momentum(resnet, neg_partial_log_likelihood, steps=FACTOR, rate=0.999)
model_momentum = LitMomentum(backbone=resnet_momentum)


# By using momentum, we can in theory reduce our batch size by factor and still have the same effective sample size
datamodule_momentum = MNISTDataModule(batch_size=BATCH_SIZE // FACTOR, transforms=transforms)

# Define trainer
trainer = L.Trainer(
    accelerator="gpu",  # Use best accelerator
    logger=False,  # No logging
    enable_checkpointing=False,  # No model checkpointing
    max_epochs=EPOCHS,  # Train for EPOCHS
    fast_dev_run=False,
    deterministic=True,
)
# Fit the model
trainer.fit(model_momentum, datamodule_momentum)
```

### Error Log:
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already
 been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True 
 if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

**Comment by tcoroller** [comment]
@Minxiangliu thanks for the code example. I created a standalone issue here #44

**Comment by ml-and-ml** [comment]
> Dear @Minxiangliu , thank you for you question. At first glance, it may be an **experimental issue (overfitting)** rather than a `TorchSurv` loss function issue.
> 
> Couple comments that may help you
> 
>     1. `Pick the right loss`: when using `cox` model, the **model optimize by ranking samples within a batch**. The larger the batch, the more reliable the loss estimation will be. When using medical image however, it may be hard to have a batch size greater than 8 samples due to GPU memory limits. Two suggestions for you: You can instead try the [Weibull model](https://opensource.nibr.com/torchsurv/_autosummary/torchsurv.loss.weibull.html), **which does not rank but fit a distribution for each sample**. It removes batch size dependancies, which is good for you. If you want to keep `cox` model, then you should try our [Momentum loss](https://opensource.nibr.com/torchsurv/_autosummary/torchsurv.loss.momentum.html), which **uses two networks (online and target) alongside a dynamic memory bank** (like MoCo for contrastive learning). We have a [tutorial notebook here](https://opensource.nibr.com/torchsurv/notebooks/momentum.html).
> 
>     2. `Data / Inputs`: You are using 189 3D images to predict a time to event target. This may be under sampled for the task. Try to reduce the covariates size (e.g., reduce image dimension, use embeddings, ..). What is your target? How many censored/non-censored patients do you have? Is there any other covariates (e.g., clinical) you can use to help the model? Is there literature on the topic that shown signal?
> 
>     3. `Modeling parameters`: What is your training/validation split? What is your batch size? And your learning rate (the loss profile looks "jumpy)? **Your training loss is decreasing close to 0, so its learning something but it is indeed very much overfitting**. There are plenty of [external ressources](https://discuss.pytorch.org/t/how-to-prevent-overfitting/1902) on overfitting that you can read and learn from.
> 
> 
> Good luck for your project and thank you for using `TorchSurv`!

I have a similar issue and am trying the Weibul loss. How is c-index used here to validate if there are 2 outputs? Do you just consider the log scale param as a risk score?
