### ISSUE TITLE
Plot Kaplan-Meier Curves Based on Model Predictions Using torchsurv?

### ISSUE THREAD

**Issue by tadongguk** [Novartis/torchsurv#63]
I am using the torchsurv library for survival analysis and want to plot Kaplan-Meier (KM) curves based on my model's predictions, not the baseline KM curve. I’m looking for guidance on how to generate these KM curves using the predictions from torchsurv. Could anyone provide advice or example code for this?
![download](https://github.com/user-attachments/assets/e0594308-1c63-4fee-8725-eac953a0a9d7)

**Comment by tadongguk** [comment]
> melodiemonod

Thank you for your response. 
I see that when using neg_partial_log_likelihood as the loss, the log_hz value is obtained from cox_model(x). Is log_hz the risk score here?

If I want to estimate the survival function, do I only need to add a function to calculate the cumulative baseline hazard using the Breslow method?

**Comment by melodiemonod** [comment]
>  Is log_hz the risk score here?

This is documented in [TorchSurv's website](https://opensource.nibr.com/torchsurv/_autosummary/torchsurv.loss.cox.html). Quoting the documentation:

> The log hazard function for the Cox proportional hazards model has the form:
> $$\log \lambda_i (t) = \log \lambda_{0}(t) + \log \theta_i$$
> where $\log \theta_i$ is the log relative hazard (argument ``log_hz``). 

The baseline hazard $\log \lambda_{0}(t)$ is not required to evaluate the partial log likelihood. As you mentioned, there are methods to estimate it, but they are not provided by our package. Nonetheless, should you be able to obtain $$\int_0^t  \log \lambda_{0}(s) ds$$, then you can evaluate the survival function of $i$ at time $t$ with

$$S_i(t) = \exp(-\log \theta_i \times \int_0^t  \log \lambda_{0}(s) ds )$$

**Comment by Minxiangliu** [comment]
Hi @melodiemonod ,
Thank you for providing the method to plot the `Kaplan-Meier curve`. I would like to ask if there is a way to plot the survival function as a non-smoothed curve, similar to your first example or the attached image.
Thank you in advance.

![Snipaste_2024-12-19_16-35-44](https://github.com/user-attachments/assets/83c69826-db50-4fe7-9ec2-b63b8c47dbf2)

**Comment by tadongguk** [comment]
> Hi @melodiemonod , Thank you for providing the method to plot the `Kaplan-Meier curve`. I would like to ask if there is a way to plot the survival function as a non-smoothed curve, similar to your first example or the attached image. Thank you in advance.
> 
> ![Snipaste_2024-12-19_16-35-44](https://private-user-images.githubusercontent.com/30144428/397299294-83c69826-db50-4fe7-9ec2-b63b8c47dbf2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1OTg2NDcsIm5iZiI6MTczNDU5ODM0NywicGF0aCI6Ii8zMDE0NDQyOC8zOTcyOTkyOTQtODNjNjk4MjYtZGI1MC00ZmU3LTllYzItYjYzYjhjNDdkYmYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDA4NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlY2VmZTE2NWFjNGQ5MGZmMjZhZDU2OTk1ODFkZDY4ZmJkNmZjMjY3YWVkZDg2NjFiMTkyZmQxMmM3ZWI5NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XI-PrSxXsa9WPc4bnUJtZ27BsIVbWZ3UrdWgLe7IJWg)

You can refer to the functions compute_baseline_hazards and predict_surv_df in pycox. By computing these, you can plot results similar to those in the image.
![75%](https://github.com/user-attachments/assets/8342b539-4dc6-4ef4-a648-45b24eea4e3c)

**Comment by Minxiangliu** [comment]
Hi @tadongguk ,
Thank you for your feedback. Do you mean that the survival prediction should use `predict_surv_df` instead of `torchsurv.loss.weibull.survival_function`?

**Comment by tadongguk** [comment]
> Hi @tadongguk , Thank you for your feedback. Do you mean that the survival prediction should use `predict_surv_df` instead of `torchsurv.loss.weibull.survival_function`?

Yes.
