### ISSUE TITLE
the link for the reference

### ISSUE THREAD

**Issue by aakhmetz** [Novartis/torchsurv#9]
Dear all,

what is the correct url for the arxiv paper? If I use: https://arxiv.org/abs/2106.13199, it goes to "A Deep Learning Approach to Private Data Sharing of Medical Images Using Conditional GANs", which is also written by Novartis researchers, but definitely not about torchsurv.

Thank you in advance,
Andrei

**Comment by melodiemonod** [comment]
Dear @aakhmetz, 

Thank you for reaching out and expressing your interest. Currently, the content you're referring to is not accessible on arXiv, and the citation provided serves as a temporary placeholder. We appreciate your patience and understanding in this matter. We'll notify you promptly once the content becomes available on arXiv, should you still be interested.

Best regards, 

Melodie

**Comment by tcoroller** [comment]
resolved in #23
